<?php

namespace Ripoo\Service;

use Ripcord\Client\Client as RipcordClient;;

/**
 * Reflect of Odoo Common Service generated by client request
 * @see https://github.com/odoo/odoo/blob/11.0/odoo/service/model.py
 *
 * @method authenticate(string $db, string $username, string $password, array $user_agent_env = []) : int
 * @method version() : array
 *
 * @author Thomas Bondois
 */
class CommonService extends RipcordClient
{
    const ENDPOINT    = 'common';

    const VERSION_ENTRY_SERVER = 'server_version';
    const VERSION_ENTRY_SERVER_INFO = 'server_version_info';
    const VERSION_ENTRY_SERVER_SERIE = 'server_serie';
    const VERSION_ENTRY_PROTOCOL = 'protocol_version';

    /**
     * Display last response XML content
     * @return string
     */
    function getRawResponse()
    {
        return $this->_response;
    }

} // end class
