<?php

namespace Ripoo\Service;

use Ripcord\Client\Client as RipcordClient;

/**
 * Reflect of Odoo Model Service generated by client request
 * @see https://github.com/odoo/odoo/blob/11.0/odoo/service/model.py
 *
 * @method execute_kw(string $db, string $uid, string $password, string $model, string $method, array $args = [], array $kwargs = null)
 * @method execute(string $db, string $uid, string $password, string $model, string $method, ...$args)
 *
 * @author Thomas Bondois
 */
class ModelService extends RipcordClient
{


} // end class
